# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import quiz_pb2 as quiz__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in quiz_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QuizServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetQuestion = channel.unary_unary(
                '/quiz.QuizService/GetQuestion',
                request_serializer=quiz__pb2.QuestionRequest.SerializeToString,
                response_deserializer=quiz__pb2.QuestionReply.FromString,
                _registered_method=True)
        self.SubmitAnswer = channel.unary_unary(
                '/quiz.QuizService/SubmitAnswer',
                request_serializer=quiz__pb2.AnswerRequest.SerializeToString,
                response_deserializer=quiz__pb2.AnswerReply.FromString,
                _registered_method=True)


class QuizServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitAnswer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuizServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuestion,
                    request_deserializer=quiz__pb2.QuestionRequest.FromString,
                    response_serializer=quiz__pb2.QuestionReply.SerializeToString,
            ),
            'SubmitAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitAnswer,
                    request_deserializer=quiz__pb2.AnswerRequest.FromString,
                    response_serializer=quiz__pb2.AnswerReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quiz.QuizService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quiz.QuizService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuizService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quiz.QuizService/GetQuestion',
            quiz__pb2.QuestionRequest.SerializeToString,
            quiz__pb2.QuestionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quiz.QuizService/SubmitAnswer',
            quiz__pb2.AnswerRequest.SerializeToString,
            quiz__pb2.AnswerReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
