# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quiz.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'quiz.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nquiz.proto\x12\x04quiz\"\x11\n\x0fQuestionRequest\"!\n\rQuestionReply\x12\x10\n\x08question\x18\x01 \x01(\t\"\x1f\n\rAnswerRequest\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\"3\n\x0b\x41nswerReply\x12\x0f\n\x07\x63orrect\x18\x01 \x01(\x08\x12\x13\n\x0b\x65xplanation\x18\x02 \x01(\t2\x80\x01\n\x0bQuizService\x12\x39\n\x0bGetQuestion\x12\x15.quiz.QuestionRequest\x1a\x13.quiz.QuestionReply\x12\x36\n\x0cSubmitAnswer\x12\x13.quiz.AnswerRequest\x1a\x11.quiz.AnswerReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quiz_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUESTIONREQUEST']._serialized_start=20
  _globals['_QUESTIONREQUEST']._serialized_end=37
  _globals['_QUESTIONREPLY']._serialized_start=39
  _globals['_QUESTIONREPLY']._serialized_end=72
  _globals['_ANSWERREQUEST']._serialized_start=74
  _globals['_ANSWERREQUEST']._serialized_end=105
  _globals['_ANSWERREPLY']._serialized_start=107
  _globals['_ANSWERREPLY']._serialized_end=158
  _globals['_QUIZSERVICE']._serialized_start=161
  _globals['_QUIZSERVICE']._serialized_end=289
# @@protoc_insertion_point(module_scope)
